import icons from "../config/icons";

export const postedTransactions = [
    {
        id: 1,
        trendimage: icons.plusdot,
        title: "Amazon",
        amount: "$1,399.00",
        status: "Missing Receipt",
        textcolor: "#874D00",
        bgcolor: "#FFFBE6",
    },
    {
        id: 2,
        trendimage: icons.plusdot,
        title: "MEDITERRANEAN CA...",
        amount: "$62.16",
        status: "Missing Receipt",
        textcolor: "#874D00",
        bgcolor: "#FFFBE6",
    },
    {
        id: 3,
        trendimage: icons.plusdot,
        title: "Chipotle",
        amount: "$13.50",
        status: "Missing Receipt",
        textcolor: "#874D00",
        bgcolor: "#FFFBE6",
    },
    {
        id: 4,
        trendimage: icons.picslip,
        title: "Lyft",
        amount: "$15.25",
        status: "Pending",
        textcolor: "#385F68",
        bgcolor: "#E2F2F8",
    },
    {
        id: 5,
        trendimage: icons.picslip,
        title: "Chick-fil-At",
        amount: "$25.50",
        status: "Complete",
        textcolor: "#206152",
        bgcolor: "#DFEEEC",
    },
    {
        id: 6,
        trendimage: icons.plusdot,
        title: "Amazon",
        amount: "$1,399.00",
        status: "Missing Receipt",
        textcolor: "#874D00",
        bgcolor: "#FFFBE6",
    },
    {
        id: 7,
        trendimage: icons.plusdot,
        title: "MEDITERRANEAN CA...",
        amount: "$62.16",
        status: "Missing Receipt",
        textcolor: "#874D00",
        bgcolor: "#FFFBE6",
    },
    {
        id: 8,
        trendimage: icons.plusdot,
        title: "Chipotle",
        amount: "$13.50",
        status: "Missing Receipt",
        textcolor: "#874D00",
        bgcolor: "#FFFBE6",
    },
    {
        id: 9,
        trendimage: icons.picslip,
        title: "Lyft",
        amount: "$15.25",
        status: "Pending",
        textcolor: "#385F68",
        bgcolor: "#E2F2F8",
    },
    {
        id: 10,
        trendimage: icons.picslip,
        title: "Chick-fil-At",
        amount: "$25.50",
        status: "Complete",
        textcolor: "#206152",
        bgcolor: "#DFEEEC",
    },
];

export default postedTransactions;
