import { ReceiptType } from "./types";

export const submittedReceipts: ReceiptType[] = [
    {
        key: '1',
        receipt: 'https://i.postimg.cc/2y6z1Qv3/receipt.png',
        receiptId: '102301',
        supplier: 'Amazon',
        amount: 20.99,
        transactionDate: '09-01-2024',
        description: 'Printer',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'pending',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
    {
        key: '2',
        receipt: '',
        receiptId: '',
        supplier: 'Amazon',
        amount: 19.99,
        transactionDate: '09-01-2024',
        description: 'Printer',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'missing',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
    {
        key: '3',
        receipt: 'https://i.postimg.cc/2y6z1Qv3/receipt.png',
        receiptId: '102303',
        supplier: 'Amazon',
        amount: 20.99,
        transactionDate: '09-01-2024',
        description: 'Printer',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'completed',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
    {
        key: '4',
        receipt: 'https://i.postimg.cc/2y6z1Qv3/receipt.png',
        receiptId: '102304',
        supplier: 'Amazon',
        amount: 20.99,
        transactionDate: '09-01-2024',
        description: 'Printer',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'completed',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
    {
        key: '5',
        receipt: 'https://i.postimg.cc/2y6z1Qv3/receipt.png',
        receiptId: '102305',
        supplier: 'Amazon',
        amount: 20.99,
        transactionDate: '09-01-2024',
        description: 'Printer',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'pending',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
    {
        key: '6',
        receipt: 'https://i.postimg.cc/2y6z1Qv3/receipt.png',
        receiptId: '102306',
        supplier: 'Amazon',
        amount: 20.99,
        transactionDate: '09-01-2024',
        description: 'Printer',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'completed',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
    {
        key: '7',
        receipt: 'https://i.postimg.cc/2y6z1Qv3/receipt.png',
        receiptId: '102307',
        supplier: 'Amazon',
        amount: 20.99,
        transactionDate: '09-01-2024',
        description: 'Printer',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'pending',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
    {
        key: '8',
        receipt: '',
        receiptId: '',
        supplier: 'Amazon',
        amount: 19.99,
        transactionDate: '09-01-2024',
        description: 'Flight to Conference',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'missing',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
    {
        key: '9',
        receipt: 'https://i.postimg.cc/2y6z1Qv3/receipt.png',
        receiptId: '102309',
        supplier: 'Amazon',
        amount: 20.99,
        transactionDate: '09-01-2024',
        description: 'Printer',
        expenseCategory: 'Office Supplies',
        multiCo: true,
        shipped: true,
        taxCharged: true,
        status: 'pending',
        user: 'Sarah',
        company: 'THE WEBSTAURANT STORE',
    },
];

export default submittedReceipts;
